apiVersion: apps/v1
kind: Deployment
metadata:
  name: coll-51ff00e52e734ad4abbc4c86f6159c8d-depl
  labels:
    app: coll-51ff00e52e734ad4abbc4c86f6159c8d
    release: prometheus  # Added label for PodMonitor discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coll-51ff00e52e734ad4abbc4c86f6159c8d
      release: prometheus  # Added label for PodMonitor discovery
  template:
    metadata:
      labels:
        app: coll-51ff00e52e734ad4abbc4c86f6159c8d
        release: prometheus  # Added label for PodMonitor discovery
    spec:
      containers:
        - name: coll-51ff00e52e734ad4abbc4c86f6159c8d
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:coll-51ff00e52e734ad4abbc4c86f6159c8d
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              name: http  # Optional for HTTP traffic
            - containerPort: 7070 #same as the deployed code
              name: metrics  # Added port for metrics scraping